nexity_rest:
    resource: "@NexityRestBundle/Controller/"
    type:     rest

nexity_back:
    resource: "@NexityBackBundle/Controller/"
    type:     annotation
    prefix:   /back

nexity_front:
    resource: "@NexityFrontBundle/Controller/"
    type:     annotation
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

