parameters:
    contact.manager.class: Nexity\BackBundle\Services\ContactManager

services:
    contact_manager:
        class: %contact.manager.class%
        arguments: [@doctrine.orm.entity_manager]