Nexity\BackBundle\Entity\Contact:
    properties:
        civilite:
            - NotBlank: ~
        nom:
            - NotBlank: ~
        prenom:
            - NotBlank: ~
        code_postal:
            - NotBlank: ~
        email:
            - NotBlank: ~
        telephone:
            - NotBlank: ~