Nexity\BackBundle\Entity\Contact:
    properties:
        civilite:
            - NotBlank:
                message: Civilité* est obligatoire
        nom:
            - NotBlank:
                message: Nom* est obligatoire
        prenom:
            - NotBlank:
                message: Prénom* est obligatoire
        code_postal:
            - NotBlank:
                message: Code Postal* est obligatoire
            - Length:
                min: 5
                max: 5
                exactMessage: Le code postal doit faire 5 chiffres
        email:
            - NotBlank:
                message: Email* est obligatoire
            - Email:
                message: Cet email "{{ value }}" est invalide
                checkMX: true
        telephone:
            - NotBlank:
                message: Téléphone* est obligatoire